// Generated by scripts/build-rubric.mjs from rubric/rubric.json. Do not edit by hand.

export type DimensionKey =
  | "frame_ownership"
  | "discovery_depth"
  | "belief_architecture"
  | "pitch_precision"
  | "tension_management"
  | "objection_resolution"
  | "qualification"
  | "strategic_awareness";

export interface Dimension {
  /** Field name in the scorer's output and on the CallRecord. */
  key: DimensionKey;
  /** Label shown in the dashboard. */
  name: string;
  /** Notion column this dimension is written to. */
  column: string;
  /** What the dimension asks — used as tooltip copy. */
  question: string;
}

export const DIMENSIONS: Dimension[] = [
  {
    key: "frame_ownership",
    name: "Frame Ownership",
    column: "Frame Ownership",
    question: "Did the caller control the conversation's direction, pacing, and agenda throughout?",
  },
  {
    key: "discovery_depth",
    name: "Discovery Depth",
    column: "Discovery Depth",
    question: "How many layers deep did the caller go?",
  },
  {
    key: "belief_architecture",
    name: "Belief Architecture",
    column: "Belief Architecture",
    question: "Were the seven buying beliefs built during the call?",
  },
  {
    key: "pitch_precision",
    name: "Pitch Precision",
    column: "Pitch Precision",
    question: "Was the pitch custom-built for this prospect, and did it sell the transformation rather than the deliverables?",
  },
  {
    key: "tension_management",
    name: "Tension Management",
    column: "Tension Management",
    question: "Could the caller hold tension without becoming needy?",
  },
  {
    key: "objection_resolution",
    name: "Objection Resolution",
    column: "Objection Resolution",
    question: "Were objections handled in the correct sequence?",
  },
  {
    key: "qualification",
    name: "Qualification",
    column: "Qualification",
    question: "Did the caller establish early whether this is a real prospect, and act on what they found?",
  },
  {
    key: "strategic_awareness",
    name: "Strategic Awareness",
    column: "Strategic Awareness",
    question: "Did the caller read the room and adapt in real time?",
  },
];

export const RUBRIC_VERSION = "1.0.0";

/** Verdict bands, highest threshold first. */
export const VERDICTS: { min: number; label: string }[] = [
  { min: 8.5, label: "Elite execution" },
  { min: 7, label: "Strong call" },
  { min: 5.5, label: "Average" },
  { min: 0, label: "Fundamentals need work" },
];

export function verdictFor(overall: number): string {
  return VERDICTS.find((v) => overall >= v.min)?.label ?? VERDICTS[VERDICTS.length - 1].label;
}
