// Generated by scripts/build-rubric.mjs from rubric/rubric.json. Do not edit by hand.

export type LeadFactorKey =
  | "pain_severity"
  | "urgency"
  | "desire_clarity"
  | "solution_belief"
  | "self_efficacy"
  | "authority"
  | "financial_capacity"
  | "icp_fit";

export interface LeadFactor {
  /** Field name in the scorer's output and on the CallRecord. */
  key: LeadFactorKey;
  /** Shown in the dashboard, and the Notion column name. */
  name: string;
  /** Notion column this factor is written to. */
  column: string;
  /** This factor's own ceiling. They differ, and they sum to LEAD_MAX. */
  max: number;
  /** The buying belief this factor measures, or null for fit. */
  belief: string | null;
  /** The scoring instruction given to the model. */
  question: string;
}

export const LEAD_FACTORS: LeadFactor[] = [
  {
    key: "pain_severity",
    name: "Pain Severity",
    column: "Pain Severity",
    max: 15,
    belief: "Pain",
    question: "How badly is the prospect's current situation actually hurting them?",
  },
  {
    key: "urgency",
    name: "Urgency",
    column: "Urgency",
    max: 15,
    belief: "Cost",
    question: "Is there a reason this has to be solved now rather than in six months?",
  },
  {
    key: "desire_clarity",
    name: "Desire Clarity",
    column: "Desire Clarity",
    max: 15,
    belief: "Desire",
    question: "Can the prospect describe the specific outcome they want?",
  },
  {
    key: "solution_belief",
    name: "Solution Belief",
    column: "Solution Belief",
    max: 15,
    belief: "Trust",
    question: "Does the prospect believe this kind of solution works?",
  },
  {
    key: "self_efficacy",
    name: "Self-Efficacy",
    column: "Self-Efficacy",
    max: 10,
    belief: "Doubt",
    question: "Does the prospect believe they can execute it, while accepting they need help to do so?",
  },
  {
    key: "authority",
    name: "Authority",
    column: "Authority",
    max: 10,
    belief: "Support",
    question: "Can this person decide alone, and do the people around them back it?",
  },
  {
    key: "financial_capacity",
    name: "Financial Capacity",
    column: "Financial Capacity",
    max: 10,
    belief: "Money",
    question: "Can the prospect actually pay what this offer costs?",
  },
  {
    key: "icp_fit",
    name: "ICP Fit",
    column: "ICP Fit",
    max: 10,
    belief: null,
    question: "Is this the kind of buyer the offer is actually built for?",
  },
];

/** What a lead scores when every factor is scored at its ceiling. */
export const LEAD_MAX = 100;

/**
 * Below this many scored factors, a Lead Score is not worth showing. A call
 * that ended in the first two minutes can produce two confident factors, and
 * scaling those two up to a number out of 100 would read as a verdict on
 * a lead nobody actually assessed.
 */
export const MIN_SCORED_FACTORS = 4;

/** Lead quality bands, highest threshold first. */
export const LEAD_BANDS: { min: number; label: string }[] = [
  { min: 75, label: "Strong" },
  { min: 55, label: "Moderate" },
  { min: 35, label: "Weak" },
  { min: 0, label: "Poor" },
];

export function leadBandFor(score: number): string {
  return LEAD_BANDS.find((b) => score >= b.min)?.label ?? LEAD_BANDS[LEAD_BANDS.length - 1].label;
}

/**
 * A lead's score out of 100, normalised over the factors that were
 * actually scored. Scoring six of eight factors gives a score out of the six
 * maximums scaled to 100, so a call that never reached the money question
 * is not punished for it — but with fewer than MIN_SCORED_FACTORS behind it,
 * there is no score at all.
 */
export function leadScore(
  scores: Record<LeadFactorKey, number | null>
): number | null {
  const scored = LEAD_FACTORS.filter((f) => scores[f.key] != null);
  if (scored.length < MIN_SCORED_FACTORS) return null;
  const got = scored.reduce((sum, f) => sum + (scores[f.key] as number), 0);
  const possible = scored.reduce((sum, f) => sum + f.max, 0);
  return Math.round((got / possible) * LEAD_MAX);
}

export interface ObjectionType {
  name: string;
  /** The buying belief the objection points at, or null. */
  belief: string | null;
  detail: string;
}

export const OBJECTION_TYPES: ObjectionType[] = [
  {
    name: "Price",
    belief: "Money",
    detail: "The number itself is the problem — too expensive, cannot afford it, needs it cheaper.",
  },
  {
    name: "Timing",
    belief: "Cost",
    detail: "Wants to start later. A better month, after something else finishes, not right now.",
  },
  {
    name: "Partner",
    belief: "Support",
    detail: "Needs to speak to a spouse, business partner, or anyone else before deciding.",
  },
  {
    name: "Think about it",
    belief: "Doubt",
    detail: "Wants to defer with no reason given. The classic stand-in for an objection they did not name.",
  },
  {
    name: "Doubts the method",
    belief: "Trust",
    detail: "Not convinced this approach works, or not convinced it works when this provider delivers it.",
  },
  {
    name: "Doubts themselves",
    belief: "Doubt",
    detail: "Believes the offer works but not that they personally will follow through on it.",
  },
  {
    name: "Tried before",
    belief: "Trust",
    detail: "A previous course, coach or programme failed them and this looks like the same thing.",
  },
  {
    name: "Comparing options",
    belief: "Trust",
    detail: "Weighing a named alternative, or shopping the category before committing.",
  },
  {
    name: "No time",
    belief: "Cost",
    detail: "Believes it works and cannot see where the hours to do it would come from.",
  },
  {
    name: "None raised",
    belief: null,
    detail: "No objection was voiced — including calls that ended before the offer was made.",
  },
];

/** The entry that means no objection was voiced, excluded from frequency counts. */
export const NO_OBJECTION = "None raised";

export const OBJECTIONS_COLUMN = "Objections";
export const PRIMARY_OBJECTION_COLUMN = "Primary Objection";
export const LEAD_SCORE_COLUMN = "Lead Score";
export const LEAD_READ_COLUMN = "Lead Read";
