// Generates every artefact that depends on the scoring rubric, so the rubric is
// written in exactly one place. Run with: npm run build:rubric
//
// Reads   rubric/rubric.json
//         rubric/offer-context.local.md      optional, gitignored — your own offer
//                                            context, injected into the chat skill
// Writes  rubric/system-prompt.txt          the system prompt the n8n workflow sends
//         rubric/output-schema.json          the JSON schema that constrains the reply
//         rubric/scorecard-rubric.md         the human-readable rubric (ships to clients)
//         rubric/skill.md                    the Claude chat skill (SKILL.md) for manual reviews
//         automation/sales-call-tracker.json the importable n8n workflow
//         src/lib/dimensions.ts              the dimension list the dashboard renders
//
// Never hand-edit the generated files — edit rubric/rubric.json (or the
// workflow template) and re-run this script.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");
const write = (p, s) => {
  writeFileSync(join(root, p), s);
  console.log(`  wrote ${p}`);
};

const rubric = JSON.parse(read("rubric/rubric.json"));

const GENERATED_BY =
  "Generated by scripts/build-rubric.mjs from rubric/rubric.json. Do not edit by hand.";

/* ------------------------------------------------------------------ prompt */

function buildSystemPrompt(r) {
  const out = [];

  out.push(
    "You are a sales call reviewer. You read the transcript of a single sales call and return a structured scorecard of that call.",
    "",
    "You are reviewing the person who was selling — referred to below as the caller. You are not reviewing the prospect.",
    "",
    "## The offer being sold",
    "",
    r.offerContextPlaceholder,
    "",
    "## How to score",
    ""
  );

  for (const p of r.scoringPrinciples) out.push(`- ${p}`);

  out.push(
    "",
    `## The ${numberWord(r.dimensions.length)} dimensions`,
    "",
    "Score each dimension from 1 to 10 and write a two-to-four sentence breakdown explaining the score with specific reference to the transcript.",
    ""
  );

  r.dimensions.forEach((d, i) => {
    out.push(`### ${i + 1}. ${d.name}`, "", d.question, "", d.detail, "", "Scoring bands:");
    for (const b of d.bands) out.push(`- ${b.range}: ${b.text}`);
    out.push("", "Look for:");
    for (const f of d.flags) out.push(`- ${f}`);
    out.push("");
  });

  out.push("## Bonus flags", "");
  for (const f of r.bonusFlags) {
    const opts =
      f.type === "enum" ? ` Answer with one of: ${f.options.join(", ")}.` : "";
    out.push(`- **${f.key}** — ${f.question}${opts}`);
  }

  out.push("", "## Written feedback", "");
  for (const n of r.narrative) out.push(`- **${n.key}** — ${n.instruction}`);

  out.push(
    "",
    "## Commercial fields",
    "",
    `Also extract the commercial facts of the call. Outcome definitions: ${r.commercial.outcomeGuide}`,
    "",
    "For any commercial field the transcript does not establish, return null rather than guessing. `lead_source` cannot be null: when the transcript never establishes where the prospect came from, answer Unknown rather than guessing.",
    "",
    "`collected_on_call` is money that actually changed hands **during the call** — a card taken while the prospect was still on the line. A deal that was agreed on the call but paid afterwards collected nothing on the call, so it is 0, not the price. Payments that land later are recorded by hand afterwards and are not your job to predict.",
    "",
    `\`currency\` is the currency the price was quoted in, one of ${r.commercial.currencies.join(", ")}. Take it from how the caller said the number — "three thousand euros" or "€3,000" is EUR, "$6,000" is USD. When no currency is stated anywhere in the call, answer ${r.commercial.defaultCurrency}. Every money field you return must be in that one currency; never convert.`,
    "",
    "`summary` is two to three sentences on what happened, written for someone who did not attend the call."
  );

  return out.join("\n") + "\n";
}

function numberWord(n) {
  return (
    ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"][n] ??
    String(n)
  );
}

/* ------------------------------------------------------------------ schema */

// Structured outputs reject `minimum`/`maximum`, so a bounded integer is
// expressed as an enum of its allowed values.
const SCORE_VALUES = Array.from({ length: 10 }, (_, i) => i + 1);

const nullable = (schema) => ({ anyOf: [schema, { type: "null" }] });

function obj(properties) {
  return {
    type: "object",
    properties,
    required: Object.keys(properties),
    additionalProperties: false,
  };
}

function buildOutputSchema(r) {
  const scores = {};
  for (const d of r.dimensions) {
    scores[d.key] = obj({
      // Nullable so a dimension the call never reached is recorded as "no
      // evidence" instead of a guessed middle score that pollutes averages.
      score: {
        anyOf: [{ type: "integer", enum: SCORE_VALUES }, { type: "null" }],
        description: `${d.question} Null when the transcript gives no evidence to judge this.`,
      },
      reasoning: {
        type: "string",
        description: `Two to four sentences justifying the ${d.name} score, quoting the transcript. When score is null, say what evidence was missing.`,
      },
    });
  }

  const flags = {};
  for (const f of r.bonusFlags) {
    flags[f.key] =
      f.type === "enum"
        ? { type: "string", enum: f.options, description: f.question }
        : { type: "boolean", description: f.question };
  }

  const narrative = {};
  for (const n of r.narrative) {
    narrative[n.key] = { type: "string", description: n.instruction };
  }

  return obj({
    outcome: { type: "string", enum: r.commercial.outcomes },
    tier: nullable({ type: "integer", enum: r.commercial.tiers }),
    price_discussed: nullable({ type: "number" }),
    price_closed: nullable({ type: "number" }),
    collected_on_call: nullable({ type: "number" }),
    // Which currency the three amounts above are in. Never converted here —
    // the dashboard applies the row's FX Rate when it totals across calls.
    currency: { type: "string", enum: r.commercial.currencies },
    payment_structure: nullable({
      type: "string",
      enum: r.commercial.paymentStructures,
    }),
    prospect_revenue: nullable({ type: "string" }),
    niche: nullable({ type: "string" }),
    location: nullable({ type: "string" }),
    lead_source: { type: "string", enum: r.commercial.leadSources },
    summary: { type: "string" },
    scores: obj(scores),
    flags: obj(flags),
    narrative: obj(narrative),
  });
}

/* ---------------------------------------------------------------- markdown */

function buildMarkdown(r) {
  const out = [`# ${r.title}`, "", `_${r.subtitle}_`, "", `<!-- ${GENERATED_BY} -->`, ""];

  out.push("## How scoring works", "");
  for (const p of r.scoringPrinciples) out.push(`- ${p}`);

  out.push("", "The overall score is the plain average of the eight dimensions.", "", "| Overall | Verdict |", "| --- | --- |");
  r.verdicts.forEach((v, i) => {
    const range =
      i === 0
        ? `${v.min.toFixed(1)}–10`
        : `${v.min.toFixed(1)}–${(r.verdicts[i - 1].min - 0.1).toFixed(1)}`;
    out.push(`| ${range} | ${v.label} |`);
  });

  out.push("", "## The dimensions", "");
  r.dimensions.forEach((d, i) => {
    out.push(`### ${i + 1}. ${d.name}`, "", `**${d.question}**`, "", d.detail, "");
    out.push("| Score | What it looks like |", "| --- | --- |");
    for (const b of d.bands) out.push(`| ${b.range} | ${b.text} |`);
    out.push("", "What the scorer looks for:", "");
    for (const f of d.flags) out.push(`- ${f}`);
    out.push("");
  });

  out.push("## Bonus flags", "", "| Flag | Question |", "| --- | --- |");
  for (const f of r.bonusFlags) out.push(`| ${f.column} | ${f.question} |`);

  out.push("", "## Written feedback", "", "Every review also produces:", "");
  for (const n of r.narrative) out.push(`- **${n.heading}** — ${n.instruction}`);

  out.push("");
  return out.join("\n");
}

/* ------------------------------------------------------------- chat skill */

// The Claude chat skill for reviewing a call manually — same rubric, same
// output shape, so a manual review can be pasted into the same Notion tracker
// the automated workflow writes to.
function buildSkill(r, offerContext) {
  const out = [];

  out.push(
    "---",
    "name: sales-call-reviewer",
    "description: Reviews sales call transcripts and produces a detailed 8-dimension scorecard with direct, transcript-specific feedback. Use this skill whenever the user shares a sales call, discovery call, or closing call transcript (or recording/notes) and wants it scored, reviewed, critiqued, analyzed, or graded — even if they don't say \"scorecard.\" Also trigger when the user asks \"how did this call go,\" \"where did I lose the deal,\" \"what should I do better next call,\" pastes call dialogue and asks for feedback, or mentions reviewing a closer's or sales rep's call. Built around the Perceptionism Lab methodology (frame, discovery depth, belief architecture, tension, objection sequencing). Do NOT use for writing scripts, hooks, captions, or content strategy — that's the perceptionism-engine skill.",
    "---",
    "",
    `<!-- ${GENERATED_BY} Rubric v${r.version}. -->`,
    "",
    "# Sales Call Reviewer",
    "",
    "You are a sales call analyst. You review the transcript of a single sales call and produce a scorecard of that call with actionable feedback.",
    "",
    "You are reviewing the person who was selling — the caller — not the prospect. If no transcript is present, ask the user to paste or upload one before scoring.",
    "",
    "## The offer being sold",
    "",
    offerContext,
    "",
    "## How to score",
    ""
  );

  for (const p of r.scoringPrinciples) out.push(`- ${p}`);

  out.push(
    "",
    `## The ${numberWord(r.dimensions.length)} dimensions`,
    "",
    "Score each dimension from 1 to 10 and write a two-to-four sentence breakdown explaining the score with specific reference to the transcript.",
    ""
  );

  r.dimensions.forEach((d, i) => {
    out.push(`### ${i + 1}. ${d.name}`, "", d.question, "", d.detail, "", "Scoring bands:");
    for (const b of d.bands) out.push(`- ${b.range}: ${b.text}`);
    out.push("", "Look for:");
    for (const f of d.flags) out.push(`- ${f}`);
    out.push("");
  });

  out.push(
    "## Overall score and verdict",
    "",
    "The overall score is the plain average of the scored dimensions (dimensions with no evidence are left out, and you say so)."
  );
  out.push("", "| Overall | Verdict |", "| --- | --- |");
  r.verdicts.forEach((v, i) => {
    const range =
      i === 0
        ? `${v.min.toFixed(1)}–10`
        : `${v.min.toFixed(1)}–${(r.verdicts[i - 1].min - 0.1).toFixed(1)}`;
    out.push(`| ${range} | ${v.label} |`);
  });

  out.push("", "## Bonus flags", "");
  for (const f of r.bonusFlags) {
    const opts = f.type === "enum" ? ` Answer with one of: ${f.options.join(", ")}.` : "";
    out.push(`- **${f.column}** — ${f.question}${opts}`);
  }

  out.push("", "## Written feedback", "", "Every review ends with these sections:", "");
  for (const n of r.narrative) out.push(`- **${n.heading}** — ${n.instruction}`);

  out.push(
    "",
    "## Output format",
    "",
    "Present the review as a readable scorecard in this order: the eight scores with the overall and verdict, then a short breakdown per dimension, then the bonus flags, then the written-feedback sections. Quote the transcript throughout.",
    "",
    "## Logging the review",
    "",
    "Pattern detection across calls (recurring weaknesses, per-closer trends) lives in the Sales Command Center dashboard, not in this chat — a review that never reaches the Notion tracker is invisible to it. So after the scorecard, offer to output the review as JSON matching the tracker's schema (`rubric/output-schema.json` in the sales-command-center repo: outcome, tier, prices, lead_source, summary, scores with reasoning, flags, narrative), so the user can add it to the tracker and keep manual and automated reviews in one dataset.",
    ""
  );

  return out.join("\n");
}

/* --------------------------------------------------------- dashboard types */

function buildDimensionsModule(r) {
  const entries = r.dimensions
    .map(
      (d) =>
        `  {\n    key: "${d.key}",\n    name: ${JSON.stringify(d.name)},\n` +
        `    plainName: ${JSON.stringify(d.plainName)},\n` +
        `    plainQuestion: ${JSON.stringify(d.plainQuestion)},\n` +
        `    column: ${JSON.stringify(d.column)},\n` +
        `    question: ${JSON.stringify(d.question)},\n  },`
    )
    .join("\n");

  const verdicts = r.verdicts
    .map((v) => `  { min: ${v.min}, label: ${JSON.stringify(v.label)} },`)
    .join("\n");

  return `// ${GENERATED_BY}

export type DimensionKey =
${r.dimensions.map((d) => `  | "${d.key}"`).join("\n")};

export interface Dimension {
  /** Field name in the scorer's output and on the CallRecord. */
  key: DimensionKey;
  /** Internal name. Matches the Notion column; not shown in the dashboard. */
  name: string;
  /** What the dashboard shows. Readable without knowing the methodology. */
  plainName: string;
  /** One line saying what this dimension is actually asking. */
  plainQuestion: string;
  /** Notion column this dimension is written to. */
  column: string;
  /** The scoring instruction given to the model. */
  question: string;
}

/** The score at or above which a dimension counts as done well. */
export const GOOD_SCORE = 7;

export const DIMENSIONS: Dimension[] = [
${entries}
];

export const RUBRIC_VERSION = ${JSON.stringify(r.version)};

/** Verdict bands, highest threshold first. */
export const VERDICTS: { min: number; label: string }[] = [
${verdicts}
];

export function verdictFor(overall: number): string {
  return VERDICTS.find((v) => overall >= v.min)?.label ?? VERDICTS[VERDICTS.length - 1].label;
}
`;
}

/* ---------------------------------------------------------------- workflow */

function buildWorkflow(r, systemPrompt, schema) {
  const template = JSON.parse(read("automation/sales-call-tracker.template.json"));
  const node = template.nodes.find((n) => n.name === "Load Rubric");
  if (!node) throw new Error("template is missing the 'Load Rubric' node");

  const assign = (name, value) => {
    const a = node.parameters.assignments.assignments.find((x) => x.name === name);
    if (!a) throw new Error(`'Load Rubric' is missing the '${name}' assignment`);
    a.value = value;
  };

  assign("system_prompt", systemPrompt);
  // Carried as a JSON string, not an n8n object assignment: the HTTP node
  // parses it back with JSON.parse. Keeping it a string avoids n8n coercing a
  // deeply nested schema on the way through.
  assign("output_schema", JSON.stringify(schema));
  assign("rubric_version", r.version);

  return template;
}

/* -------------------------------------------------------------------- run */

console.log(`Building rubric v${rubric.version} (${rubric.dimensions.length} dimensions)`);

const systemPrompt = buildSystemPrompt(rubric);
const schema = buildOutputSchema(rubric);

write("rubric/system-prompt.txt", systemPrompt);
write("rubric/output-schema.json", JSON.stringify(schema, null, 2) + "\n");
write("rubric/scorecard-rubric.md", buildMarkdown(rubric));
write("rubric/skill.md", buildSkill(rubric, rubric.offerContextPlaceholder));

// When the gitignored local offer context exists, also build the installable
// skill with the real context. Only skill.local.md gets it — the committed
// skill.md keeps the placeholder so the repo stays client-shippable.
try {
  const offerContext = read("rubric/offer-context.local.md").trim();
  write("rubric/skill.local.md", buildSkill(rubric, offerContext));
} catch {
  console.log("  no rubric/offer-context.local.md — skipping skill.local.md");
}
write("src/lib/dimensions.ts", buildDimensionsModule(rubric));
write(
  "automation/sales-call-tracker.json",
  JSON.stringify(buildWorkflow(rubric, systemPrompt, schema), null, 2) + "\n"
);

console.log("Done.");
