// Generates every artefact that depends on the scoring rubric, so the rubric is
// written in exactly one place. Run with: npm run build:rubric
//
// Reads   rubric/rubric.json
//         rubric/offer-context.local.md      optional, gitignored — your own offer
//                                            context, injected into the chat skill
// Writes  rubric/system-prompt.txt          the system prompt the n8n workflow sends
//         rubric/output-schema.json          the JSON schema that constrains the reply
//         rubric/scorecard-rubric.md         the human-readable rubric (ships to clients)
//         rubric/skill.md                    the Claude chat skill (SKILL.md) for manual reviews
//         automation/sales-call-tracker.json the importable n8n workflow
//         src/lib/dimensions.ts              the dimension list the dashboard renders
//         src/lib/lead-quality.ts            the lead factors and objection types
//
// Never hand-edit the generated files — edit rubric/rubric.json (or the
// workflow template) and re-run this script.

import { readFileSync, writeFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");
const write = (p, s) => {
  writeFileSync(join(root, p), s);
  console.log(`  wrote ${p}`);
};

const rubric = JSON.parse(read("rubric/rubric.json"));

const GENERATED_BY =
  "Generated by scripts/build-rubric.mjs from rubric/rubric.json. Do not edit by hand.";

/* ------------------------------------------------------------------ prompt */

/* QUOTING THE PROSPECT IS WHAT BROKE THE TRACKER ON 2026-08-19.

   Every reasoning field asks the model to quote the transcript, and a quoted
   phrase inside a JSON string value needs escaped double quotes. On Mason's
   call the model got stuck emitting that escape sequence: 26,626 characters of
   the same two bytes, 73% of the whole response, running straight into the
   token ceiling. The scorecard was never closed, and the first 9,950
   characters \u2014 a complete, correct scoring of the call \u2014 were thrown away.

   THE SCHEMA CANNOT PREVENT THIS. The obvious fix is a maxLength on the free
   text fields, and it is not available: Anthropic's structured-output JSON
   Schema subset does not support maxLength or minLength, and this workflow
   posts raw JSON rather than going through an SDK that would quietly strip an
   unsupported keyword. Checked against the API reference before writing a cap
   that would have been rejected on every call.

   So prompting is the lever. The rule does NOT live in this generated prompt,
   though: each client's live prompt is produced once by configure-client.mjs
   with their own offer context and then edited in n8n, so a rule added here
   reaches new clients only. It goes in the request body in the workflow
   template instead, where it is appended to whatever system prompt that client
   is running. Client-agnostic craft guidance, one home, every client. */
function buildSystemPrompt(r) {
  const out = [];

  out.push(
    "You are a sales call reviewer. You read the transcript of a single sales call and return a structured scorecard of that call.",
    "",
    "You are reviewing the person who was selling — referred to below as the caller. You are not reviewing the prospect.",
    "",
    "## The offer being sold",
    "",
    r.offerContextPlaceholder,
    "",
    "## How to score",
    ""
  );

  for (const p of r.scoringPrinciples) out.push(`- ${p}`);

  if (r.offerMatch) {
    out.push(
      "",
      `## ${r.offerMatch.heading}`,
      ""
    );
    for (const w of r.offerMatch.why) out.push(w, "");
    for (const i of r.offerMatch.instruction) out.push(`- ${i}`);
  }

  out.push(
    "",
    `## The ${numberWord(r.dimensions.length)} dimensions`,
    "",
    "Score each dimension from 1 to 10 and write a two-to-four sentence breakdown explaining the score with specific reference to the transcript.",
    ""
  );

  r.dimensions.forEach((d, i) => {
    out.push(`### ${i + 1}. ${d.name}`, "", d.question, "", d.detail, "", "Scoring bands:");
    for (const b of d.bands) out.push(`- ${b.range}: ${b.text}`);
    out.push("", "Look for:");
    for (const f of d.flags) out.push(`- ${f}`);
    out.push("");
  });

  out.push(...leadQualitySection(r, "key"));
  out.push(...objectionsSection(r));

  out.push("## Bonus flags", "");
  for (const f of r.bonusFlags) {
    const opts =
      f.type === "enum" ? ` Answer with one of: ${f.options.join(", ")}.` : "";
    out.push(`- **${f.key}** — ${f.question}${opts}`);
  }

  out.push("", "## Written feedback", "");
  for (const n of r.narrative) out.push(`- **${n.key}** — ${n.instruction}`);

  out.push(
    "",
    "## Commercial fields",
    "",
    `Also extract the commercial facts of the call. Outcome definitions: ${r.commercial.outcomeGuide}`,
    "",
    "For any commercial field the transcript does not establish, return null rather than guessing. `lead_source` cannot be null: when the transcript never establishes where the prospect came from, answer Unknown rather than guessing.",
    "",
    // THE TWO PRICE FIELDS WERE THE ONLY MONEY FIELDS NEVER DEFINED. Every
    // other one below is spelled out, and these two were left to a pair of
    // near-identical names. The model filled both with the number that was
    // quoted, so calls recorded as "No deal" arrived carrying a closed price —
    // 1,500 discussed, refused, and written down as 1,500 closed. It was not
    // inventing a sale; nothing ever told it the second field means money the
    // prospect agreed to hand over.
    /* THE PRICE RULE MOVED TO THE REQUEST BODY (2026-08-19).
       A rule written here reaches only clients configured AFTER it lands: a
       client's prompt is generated once with their own offer context and then
       lives in n8n, where this file cannot touch it. Brey's live prompt was
       built before this paragraph existed and never got it, so his scorecards
       have been recording a price that was named and refused as a price
       closed. Rules that must reach already-deployed clients ride the request
       body in the workflow template instead — see 'Writing the quotes'. */
    "",
    "`collected_on_call` is money that actually changed hands **during the call** — a card taken while the prospect was still on the line. A deal that was agreed on the call but paid afterwards collected nothing on the call, so it is 0, not the price. Payments that land later are recorded by hand afterwards and are not your job to predict.",
    "",
    `\`currency\` is the currency the price was quoted in, one of ${r.commercial.currencies.join(", ")}. Take it from how the caller said the number — "three thousand euros" or "€3,000" is EUR, "$6,000" is USD. When no currency is stated anywhere in the call, answer ${r.commercial.defaultCurrency}. Every money field you return must be in that one currency; never convert.`,
    "",
    "`summary` is two to three sentences on what happened, written for someone who did not attend the call."
  );

  return out.join("\n") + "\n";
}

function numberWord(n) {
  return (
    ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"][n] ??
    String(n)
  );
}

/* --------------------------------------------- shared prompt/skill sections */

// The lead-quality rubric, rendered once and reused by the system prompt and
// the chat skill so a manual review scores a lead exactly as the workflow does.
// `label` picks what each factor is called in the output the reader must
// produce: the prompt asks for JSON keys, the skill asks for readable names.
function leadQualitySection(r, label) {
  const lq = r.leadQuality;
  const out = [
    "",
    `## Lead quality — ${numberWord(lq.factors.length)} factors, scored out of ${lq.max}`,
    "",
    lq.intro,
    "",
    `Each factor is scored from 1 to its own maximum — a number only, with no written reason of its own. The factors carry different maximums because they do not matter equally: they sum to ${lq.max} when every one is scored. Your reading of the lead as a whole goes in lead_read, and that is where the evidence for these numbers belongs.`,
    "",
  ];

  for (const f of lq.factors) {
    const belief = f.belief ? ` · maps to the ${f.belief} belief` : "";
    out.push(
      `### ${label === "key" ? f.key : f.name} — out of ${f.max}${belief}`,
      "",
      f.question,
      "",
      f.detail,
      "",
      "Scoring bands:"
    );
    for (const b of f.bands) out.push(`- ${b.range}: ${b.text}`);
    out.push("");
  }

  out.push(
    "Patterns worth naming when you see them:",
    ...lq.patterns.map((p) => `- ${p}`),
    ""
  );

  return out;
}

function objectionsSection(r) {
  const o = r.objections;
  const out = ["", "## Objections raised", "", o.intro, ""];
  for (const t of o.types) {
    const belief = t.belief ? ` (${t.belief})` : "";
    out.push(`- **${t.name}**${belief} — ${t.detail}`);
  }
  out.push(
    "",
    "List every objection the prospect actually voiced. Then name the single one that decided the call — the one that, left unresolved, is why it did not close. When the call closed, or no objection was raised, the primary objection is null.",
    ""
  );
  return out;
}

/* ------------------------------------------------------------------ schema */

// Structured outputs reject `minimum`/`maximum`, so a bounded integer is
// expressed as an enum of its allowed values.
//
// 0 is the "no evidence" value, and it is in the enum rather than expressed as
// `null` because the API caps a schema at 16 union-typed parameters and every
// nullable field spends one. With sixteen scores plus the commercial fields,
// nullable scores put this schema at 25 and every request was refused outright
// with a 400 — silently, since nothing validates the schema until a real call
// reaches the model. Scores run from 1, so 0 cannot collide with a real one.
// It is translated back to an empty cell at the Notion write, which is the only
// place that has to know: everything downstream still reads a blank score as
// "not assessed" exactly as before.
// Two separate limits bite here, and the second only becomes visible once the
// first is satisfied. Beyond the 16-union cap, the API also refuses a schema
// whose compiled grammar is "too large" — and sixteen score fields expressed as
// enums of their allowed values were 80% of that grammar (196 of 244
// alternatives). So a score is a plain integer: the range is stated in each
// description and clamped again when the row is written, rather than enforced
// by the schema. `minimum`/`maximum` are not an option — structured outputs
// reject them.
const NO_EVIDENCE = 0;
const SCORE_MAX = 10;

/** How many union-typed parameters the API will accept in one schema. */
const UNION_LIMIT = 16;

const nullable = (schema) => ({ anyOf: [schema, { type: "null" }] });

/** Every parameter in the schema expressed as a union, at any depth. */
function countUnions(node) {
  let count = 0;
  if (node && typeof node === "object") {
    for (const value of Object.values(node.properties ?? {})) {
      if (Array.isArray(value.type) || "anyOf" in value || "oneOf" in value) count++;
      count += countUnions(value);
    }
    if (node.items && typeof node.items === "object") count += countUnions(node.items);
  }
  return count;
}

function obj(properties) {
  return {
    type: "object",
    properties,
    required: Object.keys(properties),
    additionalProperties: false,
  };
}

function buildOutputSchema(r) {
  const scores = {};
  for (const d of r.dimensions) {
    scores[d.key] = obj({
      // 0 means "no evidence", so a dimension the call never reached is
      // recorded as unjudged instead of a guessed middle score that pollutes
      // averages. See NO_EVIDENCE for why this is not `null`.
      score: {
        // A bare integer, not an enum of the allowed values. Sixteen score
        // enums were 80% of the compiled grammar and the API refused it as
        // "too large" — see SCORE_MAX. The range lives in the description and
        // is clamped again at the Notion write.
        type: "integer",
        description: `${d.question} A whole number from 1 to ${SCORE_MAX}, or ${NO_EVIDENCE} when the transcript gives no evidence to judge this.`,
      },
      reasoning: {
        type: "string",
        description: `Two to four sentences justifying the ${d.name} score, quoting the transcript. When the score is ${NO_EVIDENCE}, say what evidence was missing.`,
      },
    });
  }

  // Each lead factor has its own maximum, so each gets its own enum. 0 carries
  // the same meaning it does on the dimensions: a factor the call never reached
  // is recorded as no evidence, and the Lead Score is then averaged over the
  // factors that do have one rather than over a set padded with guesses.
  // Each factor is a bare number, not an object with its own written reason.
  // The API refuses a schema whose compiled grammar is too large, and that is
  // driven by the count of fields and nested sections rather than by enums:
  // eight factor objects with a reason each were 24 fields and 9 sections of a
  // schema that would not compile at 77 and 22. The per-factor reasons were
  // rendered only as bullets on the Notion page and read by nothing else —
  // `lead_read` already carries the reading of the lead as a whole.
  const leadFactors = {};
  for (const f of r.leadQuality.factors) {
    leadFactors[f.key] = {
      type: "integer",
      description: `${f.question} A whole number from 1 to ${f.max}, or ${NO_EVIDENCE} when the call never produced evidence either way.`,
    };
  }

  const objectionNames = r.objections.types.map((t) => t.name);

  const flags = {};
  for (const f of r.bonusFlags) {
    flags[f.key] =
      f.type === "enum"
        ? { type: "string", enum: f.options, description: f.question }
        : { type: "boolean", description: f.question };
  }

  const narrative = {};
  for (const n of r.narrative) {
    narrative[n.key] = { type: "string", description: n.instruction };
  }

  // `tier` only exists for a client whose offers actually come in tiers. With
  // none configured the field is left out of the schema altogether rather than
  // shipped as an always-null column: asking a model to fill in a band nobody
  // has defined produces a confident guess, which is what it did on Brey's
  // tracker for months. Put the numbers back in `commercial.tiers` and write
  // down what they mean, and it returns.
  const schema = obj({
    outcome: { type: "string", enum: r.commercial.outcomes },
    // Whose product was sold. Every other field on this row describes HOW the
    // call went; this one answers whether the call was ours to count at all,
    // and nothing else on the row can distinguish it.
    // Deliberately TWO FLAT FIELDS, not one nested object. Anthropic compiles
    // this schema into a validator before it will run the request, and that
    // validator has a size ceiling that nested objects spend far faster than
    // fields do. Measured against the live API at this workflow's own settings
    // (adaptive thinking, effort high) on 2026-08-25: the schema without these
    // two fields compiles, the schema plus these two flat fields compiles, and
    // the schema plus the same pair wrapped in ONE object does not — it returns
    // 400 "The compiled grammar is too large". Grouping other fields, shrinking
    // the enums and changing how nulls are written all still failed, so the
    // ceiling is about nesting, not field count. Nesting these again silently
    // stops every call being scored.
    ...(r.offerMatch
      ? {
          offer_match: {
            type: "string",
            enum: r.offerMatch.verdicts,
            description:
              `${r.offerMatch.heading} Answer "${r.offerMatch.verdicts[1]}" only when the transcript ` +
              `positively identifies a different product. Answer "${r.offerMatch.default}" whenever you cannot tell.`,
          },
          offer_evidence: {
            type: "string",
            description:
              "The line from the transcript that decides it, with its [mm:ss]. " +
              "When the verdict is unclear, say what was missing instead.",
          },
        }
      : {}),
    ...(r.commercial.tiers.length
      ? { tier: nullable({ type: "integer", enum: r.commercial.tiers }) }
      : {}),
    price_discussed: nullable({ type: "number" }),
    price_closed: nullable({ type: "number" }),
    collected_on_call: nullable({ type: "number" }),
    // Which currency the three amounts above are in. Never converted here —
    // the dashboard applies the row's FX Rate when it totals across calls.
    currency: { type: "string", enum: r.commercial.currencies },
    payment_structure: nullable({
      type: "string",
      enum: r.commercial.paymentStructures,
    }),
    prospect_revenue: nullable({ type: "string" }),
    niche: nullable({ type: "string" }),
    location: nullable({ type: "string" }),
    lead_source: { type: "string", enum: r.commercial.leadSources },
    summary: { type: "string" },
    scores: obj(scores),
    lead_quality: obj(leadFactors),
    objections: obj({
      raised: {
        type: "array",
        items: { type: "string", enum: objectionNames },
        description:
          "Every objection the prospect voiced, whether or not it was resolved. Use the single entry None raised when none was.",
      },
      primary: {
        anyOf: [{ type: "string", enum: objectionNames }, { type: "null" }],
        description:
          "The one objection that decided the call. Null when the call closed or no objection was raised.",
      },
      detail: {
        type: "string",
        description:
          "One or two sentences per objection raised: the prospect's own words with its [mm:ss], and whether the caller resolved it. Empty string when none was raised.",
      },
    }),
    flags: obj(flags),
    narrative: obj(narrative),
  });

  // The API refuses a schema with more than UNION_LIMIT union-typed parameters
  // and refuses it at request time, not at build time — so without this check
  // the failure surfaces as a 400 on a live call, days after the rubric shipped,
  // with nothing in the repo looking wrong. Rubric v1.5.0 sat live and scored
  // nothing for a day exactly this way. Fail the build instead.
  const unions = countUnions(schema);
  if (unions > UNION_LIMIT) {
    throw new Error(
      `Output schema has ${unions} union-typed parameters; the API accepts ${UNION_LIMIT}.\n` +
        `  Every nullable field spends one. Express "absent" without a union — a\n` +
        `  sentinel inside the enum, as the scores do with ${NO_EVIDENCE} — or drop a field.`
    );
  }

  return schema;
}

/* ---------------------------------------------------------------- markdown */

function buildMarkdown(r) {
  const out = [`# ${r.title}`, "", `_${r.subtitle}_`, "", `<!-- ${GENERATED_BY} -->`, ""];

  out.push("## How scoring works", "");
  for (const p of r.scoringPrinciples) out.push(`- ${p}`);

  out.push("", "The overall score is the plain average of the eight dimensions.", "", "| Overall | Verdict |", "| --- | --- |");
  r.verdicts.forEach((v, i) => {
    const range =
      i === 0
        ? `${v.min.toFixed(1)}–10`
        : `${v.min.toFixed(1)}–${(r.verdicts[i - 1].min - 0.1).toFixed(1)}`;
    out.push(`| ${range} | ${v.label} |`);
  });

  out.push("", "## The dimensions", "");
  r.dimensions.forEach((d, i) => {
    out.push(`### ${i + 1}. ${d.name}`, "", `**${d.question}**`, "", d.detail, "");
    out.push("| Score | What it looks like |", "| --- | --- |");
    for (const b of d.bands) out.push(`| ${b.range} | ${b.text} |`);
    out.push("", "What the scorer looks for:", "");
    for (const f of d.flags) out.push(`- ${f}`);
    out.push("");
  });

  const lq = r.leadQuality;
  out.push(`## Lead quality`, "", lq.intro, "");
  out.push(
    `Scored out of ${lq.max}, separately from the caller. The maximums differ because the factors do not matter equally.`,
    "",
    "| Factor | Out of | Belief | What it asks |",
    "| --- | --- | --- | --- |"
  );
  for (const f of lq.factors) {
    out.push(`| ${f.name} | ${f.max} | ${f.belief ?? "—"} | ${f.question} |`);
  }
  out.push("", "| Lead Score | Reads as |", "| --- | --- |");
  lq.bands.forEach((b, i) => {
    const range =
      i === 0 ? `${b.min}–${lq.max}` : `${b.min}–${lq.bands[i - 1].min - 1}`;
    out.push(`| ${range} | ${b.label} |`);
  });

  out.push("", "### The factors in full", "");
  lq.factors.forEach((f) => {
    out.push(`#### ${f.name} — out of ${f.max}`, "", `**${f.question}**`, "", f.detail, "");
    out.push("| Score | What it looks like |", "| --- | --- |");
    for (const b of f.bands) out.push(`| ${b.range} | ${b.text} |`);
    out.push("");
  });

  out.push("### Patterns", "");
  for (const p of lq.patterns) out.push(`- ${p}`);

  out.push("", "## Objections", "", r.objections.intro, "");
  out.push("| Objection | Belief behind it | What counts |", "| --- | --- | --- |");
  for (const t of r.objections.types) {
    out.push(`| ${t.name} | ${t.belief ?? "—"} | ${t.detail} |`);
  }

  out.push("", "## Bonus flags", "", "| Flag | Question |", "| --- | --- |");
  for (const f of r.bonusFlags) out.push(`| ${f.column} | ${f.question} |`);

  out.push("", "## Written feedback", "", "Every review also produces:", "");
  for (const n of r.narrative) out.push(`- **${n.heading}** — ${n.instruction}`);

  out.push("");
  return out.join("\n");
}

/* ------------------------------------------------------------- chat skill */

// The Claude chat skill for reviewing a call manually — same rubric, same
// output shape, so a manual review can be pasted into the same Notion tracker
// the automated workflow writes to.
function buildSkill(r, offerContext) {
  const out = [];

  out.push(
    "---",
    "name: sales-call-reviewer",
    "description: Reviews sales call transcripts and produces a detailed scorecard — eight dimensions rating the rep, eight factors rating the lead they were handed, plus the objections raised — with direct, transcript-specific feedback. Use this skill whenever the user shares a sales call, discovery call, or closing call transcript (or recording/notes) and wants it scored, reviewed, critiqued, analyzed, or graded — even if they don't say \"scorecard.\" Also trigger when the user asks \"how did this call go,\" \"where did I lose the deal,\" \"was this a good lead,\" \"what should I do better next call,\" pastes call dialogue and asks for feedback, or mentions reviewing a closer's or sales rep's call. Built around the Perceptionism Lab methodology (frame, discovery depth, belief architecture, tension, objection sequencing). Do NOT use for writing scripts, hooks, captions, or content strategy — that's the perceptionism-engine skill.",
    "---",
    "",
    `<!-- ${GENERATED_BY} Rubric v${r.version}. -->`,
    "",
    "# Sales Call Reviewer",
    "",
    "You are a sales call analyst. You review the transcript of a single sales call and produce a scorecard of that call with actionable feedback.",
    "",
    "You are reviewing the person who was selling — the caller — not the prospect. If no transcript is present, ask the user to paste or upload one before scoring.",
    "",
    "## The offer being sold",
    "",
    offerContext,
    "",
    "## How to score",
    ""
  );

  for (const p of r.scoringPrinciples) out.push(`- ${p}`);

  out.push(
    "",
    `## The ${numberWord(r.dimensions.length)} dimensions`,
    "",
    "Score each dimension from 1 to 10 and write a two-to-four sentence breakdown explaining the score with specific reference to the transcript.",
    ""
  );

  r.dimensions.forEach((d, i) => {
    out.push(`### ${i + 1}. ${d.name}`, "", d.question, "", d.detail, "", "Scoring bands:");
    for (const b of d.bands) out.push(`- ${b.range}: ${b.text}`);
    out.push("", "Look for:");
    for (const f of d.flags) out.push(`- ${f}`);
    out.push("");
  });

  out.push(
    "## Overall score and verdict",
    "",
    "The overall score is the plain average of the scored dimensions (dimensions with no evidence are left out, and you say so)."
  );
  out.push("", "| Overall | Verdict |", "| --- | --- |");
  r.verdicts.forEach((v, i) => {
    const range =
      i === 0
        ? `${v.min.toFixed(1)}–10`
        : `${v.min.toFixed(1)}–${(r.verdicts[i - 1].min - 0.1).toFixed(1)}`;
    out.push(`| ${range} | ${v.label} |`);
  });

  out.push(...leadQualitySection(r, "name"));
  out.push(...objectionsSection(r));

  out.push("", "## Bonus flags", "");
  for (const f of r.bonusFlags) {
    const opts = f.type === "enum" ? ` Answer with one of: ${f.options.join(", ")}.` : "";
    out.push(`- **${f.column}** — ${f.question}${opts}`);
  }

  out.push("", "## Written feedback", "", "Every review ends with these sections:", "");
  for (const n of r.narrative) out.push(`- **${n.heading}** — ${n.instruction}`);

  out.push(
    "",
    "## Output format",
    "",
    "Present the review as a readable scorecard in this order: the eight dimension scores with the overall and verdict, then a short breakdown per dimension, then the lead-quality factors with the Lead Score and what it reads as, then the objections raised, then the bonus flags, then the written-feedback sections. Quote the transcript throughout, with a [mm:ss] after every quote.",
    "",
    "Keep the two halves apart when you write. The dimensions say how well the call was run; the lead-quality factors say what the caller was working with. Say plainly which of the two the result came down to — an average score on a strong lead and the same score on a poor one are different problems and want different fixes.",
    "",
    "## Logging the review",
    "",
    "Pattern detection across calls (recurring weaknesses, per-closer trends) lives in the Sales Command Center dashboard, not in this chat — a review that never reaches the Notion tracker is invisible to it. So after the scorecard, offer to output the review as JSON matching the tracker's schema (`rubric/output-schema.json` in the sales-command-center repo: outcome, prices, lead_source, summary, scores with reasoning, flags, narrative), so the user can add it to the tracker and keep manual and automated reviews in one dataset.",
    ""
  );

  return out.join("\n");
}

/* --------------------------------------------------------- dashboard types */

function buildDimensionsModule(r) {
  const entries = r.dimensions
    .map(
      (d) =>
        `  {\n    key: "${d.key}",\n    name: ${JSON.stringify(d.name)},\n` +
        `    plainName: ${JSON.stringify(d.plainName)},\n` +
        `    plainQuestion: ${JSON.stringify(d.plainQuestion)},\n` +
        `    column: ${JSON.stringify(d.column)},\n` +
        `    question: ${JSON.stringify(d.question)},\n  },`
    )
    .join("\n");

  const verdicts = r.verdicts
    .map((v) => `  { min: ${v.min}, label: ${JSON.stringify(v.label)} },`)
    .join("\n");

  return `// ${GENERATED_BY}

export type DimensionKey =
${r.dimensions.map((d) => `  | "${d.key}"`).join("\n")};

export interface Dimension {
  /** Field name in the scorer's output and on the CallRecord. */
  key: DimensionKey;
  /** Internal name. Matches the Notion column; not shown in the dashboard. */
  name: string;
  /** What the dashboard shows. Readable without knowing the methodology. */
  plainName: string;
  /** One line saying what this dimension is actually asking. */
  plainQuestion: string;
  /** Notion column this dimension is written to. */
  column: string;
  /** The scoring instruction given to the model. */
  question: string;
}

/** The score at or above which a dimension counts as done well. */
export const GOOD_SCORE = 7;

export const DIMENSIONS: Dimension[] = [
${entries}
];

export const RUBRIC_VERSION = ${JSON.stringify(r.version)};

/**
 * How many dimensions must be scored before a call has an overall at all.
 * Below it the dimension scores stand on their own and the call has no place
 * on any average — a 17-minute payment call scored on two dimensions was the
 * joint top call on the board before this existed.
 */
export const MIN_SCORED_DIMENSIONS = ${JSON.stringify(r.minScoredDimensions)};

/** Verdict bands, highest threshold first. */
export const VERDICTS: { min: number; label: string }[] = [
${verdicts}
];

export function verdictFor(overall: number): string {
  return VERDICTS.find((v) => overall >= v.min)?.label ?? VERDICTS[VERDICTS.length - 1].label;
}
`;
}

function buildLeadQualityModule(r) {
  const lq = r.leadQuality;

  const factors = lq.factors
    .map(
      (f) =>
        `  {\n    key: "${f.key}",\n    name: ${JSON.stringify(f.name)},\n` +
        `    column: ${JSON.stringify(f.column)},\n` +
        `    max: ${f.max},\n` +
        `    belief: ${f.belief == null ? "null" : JSON.stringify(f.belief)},\n` +
        `    question: ${JSON.stringify(f.question)},\n  },`
    )
    .join("\n");

  const bands = lq.bands
    .map((b) => `  { min: ${b.min}, label: ${JSON.stringify(b.label)} },`)
    .join("\n");

  const objections = r.objections.types
    .map(
      (t) =>
        `  {\n    name: ${JSON.stringify(t.name)},\n` +
        `    belief: ${t.belief == null ? "null" : JSON.stringify(t.belief)},\n` +
        `    detail: ${JSON.stringify(t.detail)},\n  },`
    )
    .join("\n");

  return `// ${GENERATED_BY}

export type LeadFactorKey =
${lq.factors.map((f) => `  | "${f.key}"`).join("\n")};

export interface LeadFactor {
  /** Field name in the scorer's output and on the CallRecord. */
  key: LeadFactorKey;
  /** Shown in the dashboard, and the Notion column name. */
  name: string;
  /** Notion column this factor is written to. */
  column: string;
  /** This factor's own ceiling. They differ, and they sum to LEAD_MAX. */
  max: number;
  /** The buying belief this factor measures, or null for fit. */
  belief: string | null;
  /** The scoring instruction given to the model. */
  question: string;
}

export const LEAD_FACTORS: LeadFactor[] = [
${factors}
];

/** What a lead scores when every factor is scored at its ceiling. */
export const LEAD_MAX = ${lq.max};

/**
 * Below this many scored factors, a Lead Score is not worth showing. A call
 * that ended in the first two minutes can produce two confident factors, and
 * scaling those two up to a number out of ${lq.max} would read as a verdict on
 * a lead nobody actually assessed.
 */
export const MIN_SCORED_FACTORS = 4;

/** Lead quality bands, highest threshold first. */
export const LEAD_BANDS: { min: number; label: string }[] = [
${bands}
];

/**
 * The two thresholds the bands turn on, read off the bands themselves.
 *
 * Both numbers used to be typed again wherever a lead score was coloured — 75
 * and 55 as bare literals in the call table and the scorecard — so a band could
 * be renamed or moved here and the colours would keep the old split with
 * nothing to show for it.
 *
 * EMITTED BY THE GENERATOR, not written into the file afterwards. It was added
 * to src/lib/lead-quality.ts by hand, which that file's own header forbids, so
 * the next build deleted all three and took three tests with it — silently, in
 * a run whose visible purpose was something else entirely. A generated file is
 * only as safe as its generator.
 */
function bandMin(label: string): number {
  const band = LEAD_BANDS.find((b) => b.label === label);
  if (!band) throw new Error(\`No lead band called "\${label}"\`);
  return band.min;
}

/** At or above this, a lead is Strong. */
export const GOOD_LEAD_SCORE = bandMin("Strong");

/** At or above this but below GOOD_LEAD_SCORE, a lead is Moderate. */
export const FAIR_LEAD_SCORE = bandMin("Moderate");

export function leadBandFor(score: number): string {
  return LEAD_BANDS.find((b) => score >= b.min)?.label ?? LEAD_BANDS[LEAD_BANDS.length - 1].label;
}

/**
 * A lead's score out of ${lq.max}, normalised over the factors that were
 * actually scored. Scoring six of eight factors gives a score out of the six
 * maximums scaled to ${lq.max}, so a call that never reached the money question
 * is not punished for it — but with fewer than MIN_SCORED_FACTORS behind it,
 * there is no score at all.
 */
export function leadScore(
  scores: Record<LeadFactorKey, number | null>
): number | null {
  const scored = LEAD_FACTORS.filter((f) => scores[f.key] != null);
  if (scored.length < MIN_SCORED_FACTORS) return null;
  const got = scored.reduce((sum, f) => sum + (scores[f.key] as number), 0);
  const possible = scored.reduce((sum, f) => sum + f.max, 0);
  return Math.round((got / possible) * LEAD_MAX);
}

export interface ObjectionType {
  name: string;
  /** The buying belief the objection points at, or null. */
  belief: string | null;
  detail: string;
}

export const OBJECTION_TYPES: ObjectionType[] = [
${objections}
];

/** The entry that means no objection was voiced, excluded from frequency counts. */
export const NO_OBJECTION = ${JSON.stringify(
    r.objections.types[r.objections.types.length - 1].name
  )};

export const OBJECTIONS_COLUMN = ${JSON.stringify(r.objections.column)};
export const PRIMARY_OBJECTION_COLUMN = ${JSON.stringify(r.objections.primaryColumn)};
export const LEAD_SCORE_COLUMN = ${JSON.stringify(lq.column)};
export const LEAD_READ_COLUMN = ${JSON.stringify(lq.readColumn)};
`;
}

/* ---------------------------------------------------------------- workflow */

function buildWorkflow(r, systemPrompt, schema) {
  const template = JSON.parse(read("automation/sales-call-tracker.template.json"));
  const node = template.nodes.find((n) => n.name === "Load Rubric");
  if (!node) throw new Error("template is missing the 'Load Rubric' node");

  const assign = (name, value) => {
    const a = node.parameters.assignments.assignments.find((x) => x.name === name);
    if (!a) throw new Error(`'Load Rubric' is missing the '${name}' assignment`);
    a.value = value;
  };

  assign("system_prompt", systemPrompt);
  // Carried as a JSON string, not an n8n object assignment: the HTTP node
  // parses it back with JSON.parse. Keeping it a string avoids n8n coercing a
  // deeply nested schema on the way through.
  assign("output_schema", JSON.stringify(schema));
  assign("rubric_version", r.version);
  // The verdict bands and the overall floor travel with the prompt so the
  // Notion write reads them from the same box the rubric came from, instead of
  // keeping a typed-out copy of the thresholds that drifts from rubric.json.
  assign("verdicts", JSON.stringify(r.verdicts));
  assign("min_scored_dimensions", r.minScoredDimensions);

  return template;
}

/* ---------------------------------------------------------------- exports */

// configure-client.mjs imports these to rebuild the prompt and the schema for
// one client's own currency and tiers. It reuses the real generator rather than
// carrying a copy — a second implementation would happily agree with itself
// while disagreeing with what `npm run build:rubric` actually ships.
export { buildSystemPrompt, buildOutputSchema };

/* -------------------------------------------------------------------- run */

// Only when run directly. Importing it must not rewrite the repo's files.
const RUN_DIRECTLY =
  process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (!RUN_DIRECTLY) {
  // Nothing else to do — the caller wanted the builders, not the build.
} else {

console.log(
  `Building rubric v${rubric.version} (${rubric.dimensions.length} dimensions, ` +
    `${rubric.leadQuality.factors.length} lead factors)`
);

const systemPrompt = buildSystemPrompt(rubric);
const schema = buildOutputSchema(rubric);

write("rubric/system-prompt.txt", systemPrompt);
write("rubric/output-schema.json", JSON.stringify(schema, null, 2) + "\n");
/**
 * THE BUILD DOES NOT FINISH IF THE SCHEMA IS TOO BIG.
 *
 * Structured output compiles this schema into a grammar with a hard size
 * ceiling. Cross it and the API refuses EVERY call — Brey's tracker stops
 * receiving anything, and the only signal is a Slack alert at 10pm. That has
 * happened three times in three days, each time immediately after a rubric
 * edit, which is exactly this step.
 *
 * Gated here rather than left as a separate command, because a check someone
 * has to remember is a check that gets skipped on the night it matters. It
 * runs BEFORE the workflow is written, so a refused schema never reaches the
 * file n8n imports.
 */
const guard = spawnSync(process.execPath, [join(root, "scripts/check-schema.mjs")], {
  stdio: "inherit",
});
if (guard.status !== 0) {
  console.error(
    "\nBuild stopped: the generated schema would be refused by the API.\n" +
      "The workflow was NOT rewritten, so the live one still works. Shrink the\n" +
      "rubric and re-run.\n"
  );
  process.exit(1);
}

write("rubric/scorecard-rubric.md", buildMarkdown(rubric));
write("rubric/skill.md", buildSkill(rubric, rubric.offerContextPlaceholder));

// When the gitignored local offer context exists, also build the installable
// skill with the real context. Only skill.local.md gets it — the committed
// skill.md keeps the placeholder so the repo stays client-shippable.
try {
  const offerContext = read("rubric/offer-context.local.md").trim();
  write("rubric/skill.local.md", buildSkill(rubric, offerContext));
} catch {
  console.log("  no rubric/offer-context.local.md — skipping skill.local.md");
}
write("src/lib/dimensions.ts", buildDimensionsModule(rubric));
write("src/lib/lead-quality.ts", buildLeadQualityModule(rubric));
write(
  "automation/sales-call-tracker.json",
  JSON.stringify(buildWorkflow(rubric, systemPrompt, schema), null, 2) + "\n"
);

console.log("Done.");

}
