// Generates every artefact that depends on the scoring rubric, so the rubric is
// written in exactly one place. Run with: npm run build:rubric
//
// Reads   rubric/rubric.json
// Writes  rubric/system-prompt.txt          the system prompt the n8n workflow sends
//         rubric/output-schema.json          the JSON schema that constrains the reply
//         rubric/scorecard-rubric.md         the human-readable rubric (ships to clients)
//         automation/sales-call-tracker.json the importable n8n workflow
//         src/lib/dimensions.ts              the dimension list the dashboard renders
//
// Never hand-edit the four generated files — edit rubric/rubric.json (or the
// workflow template) and re-run this script.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const read = (p) => readFileSync(join(root, p), "utf8");
const write = (p, s) => {
  writeFileSync(join(root, p), s);
  console.log(`  wrote ${p}`);
};

const rubric = JSON.parse(read("rubric/rubric.json"));

const GENERATED_BY =
  "Generated by scripts/build-rubric.mjs from rubric/rubric.json. Do not edit by hand.";

/* ------------------------------------------------------------------ prompt */

function buildSystemPrompt(r) {
  const out = [];

  out.push(
    "You are a sales call reviewer. You read the transcript of a single sales call and return a structured scorecard of that call.",
    "",
    "You are reviewing the person who was selling — referred to below as the caller. You are not reviewing the prospect.",
    "",
    "## The offer being sold",
    "",
    r.offerContextPlaceholder,
    "",
    "## How to score",
    ""
  );

  for (const p of r.scoringPrinciples) out.push(`- ${p}`);

  out.push(
    "",
    `## The ${numberWord(r.dimensions.length)} dimensions`,
    "",
    "Score each dimension from 1 to 10 and write a two-to-four sentence breakdown explaining the score with specific reference to the transcript.",
    ""
  );

  r.dimensions.forEach((d, i) => {
    out.push(`### ${i + 1}. ${d.name}`, "", d.question, "", d.detail, "", "Scoring bands:");
    for (const b of d.bands) out.push(`- ${b.range}: ${b.text}`);
    out.push("", "Look for:");
    for (const f of d.flags) out.push(`- ${f}`);
    out.push("");
  });

  out.push("## Bonus flags", "");
  for (const f of r.bonusFlags) {
    const opts =
      f.type === "enum" ? ` Answer with one of: ${f.options.join(", ")}.` : "";
    out.push(`- **${f.key}** — ${f.question}${opts}`);
  }

  out.push("", "## Written feedback", "");
  for (const n of r.narrative) out.push(`- **${n.key}** — ${n.instruction}`);

  out.push(
    "",
    "## Commercial fields",
    "",
    `Also extract the commercial facts of the call. Outcome definitions: ${r.commercial.outcomeGuide}`,
    "",
    "For any commercial field the transcript does not establish, return null rather than guessing. `cash_collected` is the amount actually taken on the call — the same as `price_closed` when the prospect paid in full.",
    "",
    "`summary` is two to three sentences on what happened, written for someone who did not attend the call."
  );

  return out.join("\n") + "\n";
}

function numberWord(n) {
  return (
    ["zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten"][n] ??
    String(n)
  );
}

/* ------------------------------------------------------------------ schema */

// Structured outputs reject `minimum`/`maximum`, so a bounded integer is
// expressed as an enum of its allowed values.
const SCORE_VALUES = Array.from({ length: 10 }, (_, i) => i + 1);

const nullable = (schema) => ({ anyOf: [schema, { type: "null" }] });

function obj(properties) {
  return {
    type: "object",
    properties,
    required: Object.keys(properties),
    additionalProperties: false,
  };
}

function buildOutputSchema(r) {
  const scores = {};
  for (const d of r.dimensions) {
    scores[d.key] = obj({
      score: { type: "integer", enum: SCORE_VALUES, description: d.question },
      reasoning: {
        type: "string",
        description: `Two to four sentences justifying the ${d.name} score, quoting the transcript.`,
      },
    });
  }

  const flags = {};
  for (const f of r.bonusFlags) {
    flags[f.key] =
      f.type === "enum"
        ? { type: "string", enum: f.options, description: f.question }
        : { type: "boolean", description: f.question };
  }

  const narrative = {};
  for (const n of r.narrative) {
    narrative[n.key] = { type: "string", description: n.instruction };
  }

  return obj({
    outcome: { type: "string", enum: r.commercial.outcomes },
    tier: nullable({ type: "integer", enum: r.commercial.tiers }),
    price_discussed: nullable({ type: "number" }),
    price_closed: nullable({ type: "number" }),
    cash_collected: nullable({ type: "number" }),
    payment_structure: nullable({
      type: "string",
      enum: r.commercial.paymentStructures,
    }),
    prospect_revenue: nullable({ type: "string" }),
    niche: nullable({ type: "string" }),
    location: nullable({ type: "string" }),
    lead_source: { type: "string", enum: r.commercial.leadSources },
    summary: { type: "string" },
    scores: obj(scores),
    flags: obj(flags),
    narrative: obj(narrative),
  });
}

/* ---------------------------------------------------------------- markdown */

function buildMarkdown(r) {
  const out = [`# ${r.title}`, "", `_${r.subtitle}_`, "", `<!-- ${GENERATED_BY} -->`, ""];

  out.push("## How scoring works", "");
  for (const p of r.scoringPrinciples) out.push(`- ${p}`);

  out.push("", "The overall score is the plain average of the eight dimensions.", "", "| Overall | Verdict |", "| --- | --- |");
  r.verdicts.forEach((v, i) => {
    const range =
      i === 0
        ? `${v.min.toFixed(1)}–10`
        : `${v.min.toFixed(1)}–${(r.verdicts[i - 1].min - 0.1).toFixed(1)}`;
    out.push(`| ${range} | ${v.label} |`);
  });

  out.push("", "## The dimensions", "");
  r.dimensions.forEach((d, i) => {
    out.push(`### ${i + 1}. ${d.name}`, "", `**${d.question}**`, "", d.detail, "");
    out.push("| Score | What it looks like |", "| --- | --- |");
    for (const b of d.bands) out.push(`| ${b.range} | ${b.text} |`);
    out.push("", "What the scorer looks for:", "");
    for (const f of d.flags) out.push(`- ${f}`);
    out.push("");
  });

  out.push("## Bonus flags", "", "| Flag | Question |", "| --- | --- |");
  for (const f of r.bonusFlags) out.push(`| ${f.column} | ${f.question} |`);

  out.push("", "## Written feedback", "", "Every review also produces:", "");
  for (const n of r.narrative) out.push(`- **${n.heading}** — ${n.instruction}`);

  out.push("");
  return out.join("\n");
}

/* --------------------------------------------------------- dashboard types */

function buildDimensionsModule(r) {
  const entries = r.dimensions
    .map(
      (d) =>
        `  {\n    key: "${d.key}",\n    name: ${JSON.stringify(d.name)},\n    column: ${JSON.stringify(
          d.column
        )},\n    question: ${JSON.stringify(d.question)},\n  },`
    )
    .join("\n");

  const verdicts = r.verdicts
    .map((v) => `  { min: ${v.min}, label: ${JSON.stringify(v.label)} },`)
    .join("\n");

  return `// ${GENERATED_BY}

export type DimensionKey =
${r.dimensions.map((d) => `  | "${d.key}"`).join("\n")};

export interface Dimension {
  /** Field name in the scorer's output and on the CallRecord. */
  key: DimensionKey;
  /** Label shown in the dashboard. */
  name: string;
  /** Notion column this dimension is written to. */
  column: string;
  /** What the dimension asks — used as tooltip copy. */
  question: string;
}

export const DIMENSIONS: Dimension[] = [
${entries}
];

export const RUBRIC_VERSION = ${JSON.stringify(r.version)};

/** Verdict bands, highest threshold first. */
export const VERDICTS: { min: number; label: string }[] = [
${verdicts}
];

export function verdictFor(overall: number): string {
  return VERDICTS.find((v) => overall >= v.min)?.label ?? VERDICTS[VERDICTS.length - 1].label;
}
`;
}

/* ---------------------------------------------------------------- workflow */

function buildWorkflow(r, systemPrompt, schema) {
  const template = JSON.parse(read("automation/sales-call-tracker.template.json"));
  const node = template.nodes.find((n) => n.name === "Load Rubric");
  if (!node) throw new Error("template is missing the 'Load Rubric' node");

  const assign = (name, value) => {
    const a = node.parameters.assignments.assignments.find((x) => x.name === name);
    if (!a) throw new Error(`'Load Rubric' is missing the '${name}' assignment`);
    a.value = value;
  };

  assign("system_prompt", systemPrompt);
  // Carried as a JSON string, not an n8n object assignment: the HTTP node
  // parses it back with JSON.parse. Keeping it a string avoids n8n coercing a
  // deeply nested schema on the way through.
  assign("output_schema", JSON.stringify(schema));
  assign("rubric_version", r.version);

  return template;
}

/* -------------------------------------------------------------------- run */

console.log(`Building rubric v${rubric.version} (${rubric.dimensions.length} dimensions)`);

const systemPrompt = buildSystemPrompt(rubric);
const schema = buildOutputSchema(rubric);

write("rubric/system-prompt.txt", systemPrompt);
write("rubric/output-schema.json", JSON.stringify(schema, null, 2) + "\n");
write("rubric/scorecard-rubric.md", buildMarkdown(rubric));
write("src/lib/dimensions.ts", buildDimensionsModule(rubric));
write(
  "automation/sales-call-tracker.json",
  JSON.stringify(buildWorkflow(rubric, systemPrompt, schema), null, 2) + "\n"
);

console.log("Done.");
